### ISSUE TITLE
Remove installation of ShellCheck from .travis.yml

### ISSUE THREAD

**Issue by EvgenyOrekhov** [PHP-CS-Fixer/trailing-whitespace-checker#9]
ShellCheck is integrated into Travis CI, there is no need in installing it using `apt-get`.

https://github.com/PHP-CS-Fixer/trailing-whitespace-checker/blob/fa2c59acf6b71fd4d8f3ad82186944f46407fed1/.travis.yml#L7

`apt-get` here actually installs an outdated version of ShellCheck (0.3.3). Travis CI is bundled with ShellCheck 0.4.6.

**Comment by keradus** [comment]
sounds good. please, raise a PR ;)
